# Generated by Django 3.1.7 on 2021-03-31 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='path',
            field=models.CharField(default='images/lobos.jpg', max_length=100, verbose_name='Path'),
        ),
    ]
